export const employeeInfo = [
  {
    name: "Yanchou Han",
    title: "IAM Architect",
    linkedin: "https://www.linkedin.com/in/yanchou-han-b87ba5/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guptarh2lkj604u04ua9x02.jpg",
  },
  {
    name: "Bin Lin",
    title: "Senior IAM Consultant",
    linkedin: "https://www.linkedin.com/in/bin-lin-25011110/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupxrmkkgpj60hs0hsjry02.jpg",
  },
  {
    name: "Le Deng",
    title: "Senior IAM Consultant",
    linkedin: "https://www.linkedin.com/in/le-deng-82829710a/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupt6s9vzjj60e80e8jsa02.jpg",
  },
  {
    name: "Lei Zhang",
    title: "Senior IAM Consultant",
    linkedin: "https://www.linkedin.com/in/lei-zhang-a5245a43/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guq1770rx5j60b40b4mxx02.jpg",
  },
  {
    name: "Jiayi Cai",
    title: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/jiayi-cai-8b7093136/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guqaxic3m3j60b40b4jro02.jpg",
  },
  {
    name: "Steve Mu",
    title: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/qistevemu/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupt7w706zj60dw0dw3zz02.jpg",
  },
  {
    name: "Lingchao Jiang",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/lingchao-jiang-90a181128/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupuhoa89jj60b40b4mxe02.jpg",
  },
  {
    name: "Zixiao Zheng",
    title: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/zixiao-zheng-b40a03163/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guqax7bo3hj60e50e5wfm02.jpg",
  },
  {
    name: "Yunfei Xu",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/yunfei-xu-b08319157/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guptdbhazpj60j60j6jsj02.jpg",
  },
  {
    name: "Xiaohan Li",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/xiaohan-li-28a115180/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guptac8v02j60gq0gq3yx02.jpg",
  },
  {
    name: "Chaopeng Hu",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/chaopeng-hu-15b529175/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupt3p8g8ej60u00u0aeh02.jpg",
  },
  {
    name: "Yishu Sun",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/yishusun-it/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guptc9cnu3j60u0140q7j02.jpg",
  },
  {
    name: "Chance Liu",
    title: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/chanceliu/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guqardqcppj6070071gls02.jpg",
  },
  /*
  {
    name: "Yongzheng Sun",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/yongzheng-sun-34b15814b/",
    pic: "",
  },
  */
  {
    name: "Jie Dai",
    title: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/jie-dai-aa817a14b/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupt62z7p5j60u013yn6u02.jpg",
  },
  {
    name: "Yifu Xu",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/yifu-xu-8b9936172/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupxka9jp0j60u00u041g02.jpg",
  },
  {
    name: "Jiawei Zhao",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/jiawei-zhao-913935172/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guptkggc97j60dw0dwdgm02.jpg",
  },
  {
    name: "Wenhao Liu",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/wenhao-liu-4a351517a/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupt95dpt9j60b40b4wep02.jpg",
  },
  {
    name: "Chen Wang",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/chen-wang7/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupyck2mx6j60ia0iaaaz02.jpg",
  },
  {
    name: "Shujian Chen",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/shujian-kevin-chen/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupxl2imluj60u00u0ado02.jpg",
  },
  {
    name: "Tao Xu",
    title: "IAM Consultant",
    linkedin: "https://www.linkedin.com/in/xu-tao/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupt9tvoa3j60gq0gqt9p02.jpg",
  },
  {
    name: "Weili Yin",
    title: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/charlesywl/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupt8c4uimj60m80m8myy02.jpg",
  },
  {
    name: "Hao Luo",
    title: "IAM Engineer Intern",
    linkedin: "https://www.linkedin.com/in/hao-luo-27a08a16b/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupt4plzgtj60b40b40t102.jpg",
  },
  {
    name: "Shuwan Yao",
    title: "IAM Engineer Intern",
    linkedin: "https://www.linkedin.com/in/shuwan-yao-columbia-nyc/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1gupt794a4lj60u70u042u02.jpg",
  },
  {
    name: "Yifeng Shi",
    title: "IAM Engineer Intern",
    linkedin: "https://www.linkedin.com/in/yifeng-carl-shi-a20156aa/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guptbbh0xzj60cg0cgt9002.jpg",
  },
  {
    name: "Yu Zhan",
    title: "IAM Engineer Intern",
    linkedin: "https://www.linkedin.com/in/yuzhan-student/",
    pic: "https://tva1.sinaimg.cn/large/008i3skNgy1guptcqtd5wj60gq0gq0tc02.jpg",
  },
];
